FLASK_DATABASE_URI = sqlite:///database.db
FLASK_DEBUG = 1
FLASK_RUN_HOST = 130.104.12.28
FLASK_RUN_PORT = 80
FLASK_STATIC_PATH = /lelec210x

# Comment the two next lines on the server
FLASK_RUN_HOST = 0.0.0.0
FLASK_RUN_PORT = 5000

FLASK_PROFILER = 0
