name: Bug
description: Report an issue to help improve the project.
title: <short-description-here>
labels: [bug]

body:
- type: markdown
  id: preamble
  attributes:
    value: |
      **Thank you for reporting a problem!**

      If you know how to solve your problem, feel free to submit a PR too!

- type: checkboxes
  id: terms
  attributes:
    label: Terms
    description: 'By submitting this issue, I have:'
    options:
    - label: Checked the [existing issues](https://github.com/LELEC210X/LELEC210X/issues?q=is%3Aissue) and [discussions](https://github.com/LELEC210X/LELEC210X/discussions) to see if my issue had not already been reported;
      required: true
    - label: Read the [best practice](https://github.com/LELEC210X/LELEC210X/wiki/Best-practice-guide) and checked if my bug was not one of the common bugs documented in the Wiki;
      required: true
    - label: Updated my Python virtual environment with `rye sync`;
      required: true

- type: textarea
  id: description
  attributes:
    label: Describe the issue
    description: A description of the issue, also include what you tried and what didn't work.
  validations:
    required: true

- type: input
  id: command
  attributes:
    label: Command or program
    description: |
      Enter the command or program that failed.
      This will be automatically formatted into code, so no need for backticks.
      If the bug occred inside a program, like GNU Radio, insert the name of the program.
    placeholder: rye sync
  validations:
    required: true

- type: dropdown
  id: issue-type
  attributes:
    label: Issue Type
    description: >
      Please select the option in the drop-down.
    options:
    - Installation issue
    - Error when running an command
    - Unexpected results (e.g., packets are wrong)
    - Issue with the GitHub repository (e.g., updating your fork)
    - Other
  validations:
    required: true

- type: dropdown
  id: platform
  attributes:
    label: What is your platform?
    multiple: true
    options:
    - Linux (dual boot)
    - Linux (Virtual Box)
    - Linux (WSL)
    - macOS
    - Windows
    - Other (please precise below)
  validations:
    required: true

- type: input
  id: platform-other
  attributes:
    label: Other platform
    description: Please answer if you have replied *Other* above.
  validations:
    required: false

- type: textarea
  id: logs
  attributes:
    label: Relevant error output
    description: |
      Please copy and paste any relevant error output.
      This will be automatically formatted into code, so no need for backticks.
    render: shell
  validations:
    required: false

- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: Please add screenshots if applicable.
  validations:
    required: false

- type: textarea
  id: extra-info
  attributes:
    label: Additional information
    description: Is there anything else we should know about this bug?
  validations:
    required: false

- type: textarea
  id: suggested-fix
  attributes:
    label: Recommended fix or suggestions
    description: A clear and concise description of how you want to update it.
  validations:
    required: false
